### PR TITLE
Replace TTFs with WOFF2

### PR DESCRIPTION
**Pull request by ndorfin**
Follow on from #4 

### In this PR

- Replace TTFs binaries with WOFF2 ones.
- Subset the WOFF2s, further reducing file-size
- Update `@font-face` blocks.
- Add `local()` src defs too.

### Improvements

- File size for font binaries dropped from 468kB to 34kB (Saving 434kB)
- If the user has Noto Sans and Noto Sans Mono installed locally, the browser will use those binaries rather than requesting them over the network.

### Comments

I've included WOFF2s that aren't subset, in case you want to roll back to the originals.

### Performance metrics

Before merging this PR, be sure to create a 3-run cached and uncached WebPageTest.org test of your site from your desired testing location.
Once you merge this PR, run the same test with a different label. You'll then be able to compare the differences in performance.

### CODE REVIEW

**Comment by ecruzolivera** [comment]
thanks again!!

**Comment by ndorfin** [comment]
It's a pleasure @ecruzolivera 
What do the measured performance improvements look like? :)

**Comment by ndorfin** [comment]
I had an old test of your homepage on WebPageTest.org
Comparing that to a test I ran today:
https://www.webpagetest.org/video/compare.php?tests=240726_BiDc4J_610,240715_BiDcDQ_39Z

Less layout shifts! Nice.
The new CSS request is blocking rendering though - which is why the site now takes longer to render.

**Comment by ecruzolivera** [comment]
right, I ran the tests, and i saw the difference, but the site is way smaller, and still loads quite fast, or at least fast enough for a blog

**Comment by ndorfin** [comment]
@ecruzolivera All good - I'm glad you're free of the 'I WANT MORE SPEED!' bug :D

**Pull request merged**
